// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/casaevideo.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$1 from "./loaders/availableIcons.ts";
import * as $$$2 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/List/Sections.tsx";

const manifest = {
  "loaders": {
    "deco-sites/lebiscuit/loaders/availableIcons.ts": $$$1,
    "deco-sites/lebiscuit/loaders/icons.ts": $$$2,
    "deco-sites/lebiscuit/loaders/List/Sections.tsx": $$$0,
  },
  "apps": {
    "deco-sites/lebiscuit/apps/casaevideo.ts": $$$$$$$$$$$0,
    "deco-sites/lebiscuit/apps/decohub.ts": $$$$$$$$$$$1,
    "deco-sites/lebiscuit/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "deco-sites/lebiscuit",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
