// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/casaevideo.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";

const manifest = {
  "apps": {
    "deco-sites/lebiscuit/apps/casaevideo.ts": $$$$$$$$$$$0,
    "deco-sites/lebiscuit/apps/decohub.ts": $$$$$$$$$$$1,
    "deco-sites/lebiscuit/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "deco-sites/lebiscuit",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
